# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CodeIntent
email: codeIntent2018@gmail.com
description: "Esse é um blog desenvolvidos em Jekyll."
baseurl: ""
url: "http://codeIntern2018.github.io"
github_username:  codeIntern2018

# Build settings
markdown: kramdown
permalink: /:title/
